# Default values for redis-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 6

fullnameOverride: "redis-cluster"

redisService:
  type: NodePort
  port: 6379

exporterService:
  port: 16379

storageClassName:
  name: "nfs-client"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 500m
  #  memory: 1Gi
  # requests:
  #  cpu: 500m
  #  memory: 1Gi


